# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Setup
title:            Anand Dsouza
tagline:          ''
description:      'Senior Product Developer'
url:              
baseurl:          /

# author:
  # name:           'Anand Dsouza'
  # url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ananddsouza/hyde

root: /_site
